### edit PORT number in this line add token after log-in
@BASE_URL=http://localhost:3300
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA3MTcwODksImV4cCI6MTczMDcyMDY4OX0._iJtIjlQgPKDLvpFi6cR_qQsTRYQxbAile2Tl5nVxoI
###register new user
POST {{BASE_URL}}/api/users/register
Content-Type: application/json

{
  "username": "test user5",
  "email": "tes4@example.com",
  "password": "123456",
  "role": "admin"
}


### login user
POST {{BASE_URL}}/api/users/login
Content-Type: application/json

{
  "email": "tes5@example.com",
  "password": "123456"
}


### Listar usuarios
GET {{BASE_URL}}/api/users/list
Authorization: Bearer {{TOKEN}}

### Ban User
DELETE {{BASE_URL}}/api/users/ban
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "userId":5
}


### Post publication
POST {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "La senda de las brujas",
  "content": "larga, yerma y cruel",
  "authorId": 4
}

### Edit Publication
PATCH  {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "publicationId":3,
  "title": "editando titulo brujas3"
 
}

### Delete Publication
DELETE {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Autorization: Bearer {{TOKEN}}

{
  "publicationId": 4,
"deleted":true
}

### Eliminate Publication
DELETE {{BASE_URL}}/api/publications/delete-publication
Content-Type: application/json
Autorization: Bearer {{TOKEN}}

{
  "publicationId": 9
}


### like Publication
POST {{BASE_URL}}/api/publications/like
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "userId": 4,
  "publicationId": 12
}

