### edit PORT number in this line add token after log-in
@BASE_URL=http://localhost:3300
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJSb2xlIjoic2ltcGxlVXNlciIsImlhdCI6MTczMDgwOTMyOSwiZXhwIjoxNzMwODEyOTI5fQ.kCqETEAvGunpKr7tpH1ZdVELjOMUnSve6NufPCuDZQY

### Register User
POST {{BASE_URL}}/api/users/register
Content-Type: application/json

{
  "username": "ADMIN",
  "email": "tes11@example.com",
  "password": "123456",
  "role": "admin"
}


### login user
POST {{BASE_URL}}/api/users/login
Content-Type: application/json

{
  "email": "tes8@example.com",
  "password": "123456"
}
### Obtener todas las publicaciones 
GET {{BASE_URL}}/api/publications
Content-Type: application/json 
Authorization: Bearer {{TOKEN}}

### Listar usuarios
GET {{BASE_URL}}/api/users/list
Authorization: Bearer {{TOKEN}}

### Ban User
DELETE {{BASE_URL}}/api/users/ban
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "userId":5
}


### Post publication
POST {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Simple usuario",
  "content": "simple publicacion9"
}

### Edit Publication
PATCH  {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "publicationId":21,
  "content": "simple pero muy que simplex2"
 
}

### SoftDelete Publication
DELETE {{BASE_URL}}/api/publications/publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "publicationId": 21
}

### Eliminate Publication
DELETE {{BASE_URL}}/api/publications/delete-publication
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "publicationId": 21
}


### like Publication
POST {{BASE_URL}}/api/publications/like
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "publicationId": 11
}

