POST http://localhost:3300/api/users/register
Content-Type: application/json

{
  "username": "test user3",
  "email": "tes3@example.com",
  "password": "123456",
  "role": "admin"
}
###
Post http://localhost:3300/api/users/login
Content-Type: application/json
{
  "email": "tes3@example.com",
  "password": "123456"
 
}

###

POST http://localhost:3300/api/publications/publication
Content-Type: application/json

{
  "title": "Arquitectura Limpia",
  "content": "pueba",
  "authorId": 2
}
