### edit PORT number in this line
@BASE_URL=http://localhost:3300

###register new user
POST {{BASE_URL}}/api/users/register
Content-Type: application/json

{
  "username": "test user3",
  "email": "tes3@example.com",
  "password": "123456",
  "role": "admin"
}
### login user
Post {{BASE_URL}}/api/users/login
Content-Type: application/json

{
  "email": "tes2@example.com",
  "password": "123456"
}

### Post publication

POST {{BASE_URL}}/api/publications/publication
Content-Type: application/json

{
  "title": "Arquitectura Limpia",
  "content": "pueba",
  "authorId": 1
}


### like Publication
POST {{BASE_URL}}/api/publications/like
Content-Type: application/json

{
  "userId": 3,
  "publicationId": 2
}
